# Generated by Django 5.1.4 on 2025-01-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='content',
            new_name='css_content',
        ),
        migrations.AddField(
            model_name='template',
            name='html_content',
            field=models.TextField(null='False'),
            preserve_default='False',
        ),
    ]
