# Generated by Django 5.1.4 on 2025-01-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumedetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resumedetails',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='resumedetails',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumedetails',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resumedetails',
            name='experience',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resumedetails',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resumedetails',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
