# Generated by Django 5.1.4 on 2025-01-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details_api', '0002_remove_resumedetails_created_at_and_more'),
    ]

    operations = [
    ]
