# Generated by Django 5.1.4 on 2025-02-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_api', '0003_auto_20250123_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedetails',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumedetails',
            name='projects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resumedetails',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
